src/Entity/RegistrationCodes.php
<?php

namespace App\Entity;

use App\Repository\RegistrationCodesRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RegistrationCodesRepository::class)]
class RegistrationCodes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 10, unique: true)]
    private ?string $code = null;

    #[ORM\Column(options: ['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\ManyToOne(inversedBy: 'registrationCodes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Users $created_by = null;

    #[ORM\Column(options: ['default' => 'TRUE'])]
    private ?bool $is_available = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Users $used_by = null;

    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
        $this->is_available = true;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): static
    {
        $this->code = $code;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCreatedBy(): ?Users
    {
        return $this->created_by;
    }

    public function setCreatedBy(?Users $created_by): static
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function isIsAvailable(): ?bool
    {
        return $this->is_available;
    }

    public function setIsAvailable(bool $is_available): static
    {
        $this->is_available = $is_available;

        return $this;
    }

    public function getUsedBy(): ?Users
    {
        return $this->used_by;
    }

    public function setUsedBy(?Users $used_by): static
    {
        $this->used_by = $used_by;

        return $this;
    }
}

src/Entity/Users.php
<?php

namespace App\Entity;

use App\Repository\UsersRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UsersRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'Email déjà utilisé')]
class Users implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 100)]
    private ?string $name = null;

    #[ORM\Column(length: 100)]
    private ?string $lastname = null;

    #[ORM\Column(options: ['default' => 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\OneToMany(targetEntity: RegistrationCodes::class, mappedBy: 'created_by', orphanRemoval: true)]
    private Collection $registrationCodes;

    #[ORM\OneToMany(targetEntity: Images::class, mappedBy: 'owner', orphanRemoval: true)]
    private Collection $images;

    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
        $this->registrationCodes = new ArrayCollection();
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): static
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, RegistrationCodes>
     */
    public function getRegistrationCodes(): Collection
    {
        return $this->registrationCodes;
    }

    public function addRegistrationCode(RegistrationCodes $registrationCode): static
    {
        if (!$this->registrationCodes->contains($registrationCode)) {
            $this->registrationCodes->add($registrationCode);
            $registrationCode->setCreatedBy($this);
        }

        return $this;
    }

    public function removeRegistrationCode(RegistrationCodes $registrationCode): static
    {
        if ($this->registrationCodes->removeElement($registrationCode)) {
            // set the owning side to null (unless already changed)
            if ($registrationCode->getCreatedBy() === $this) {
                $registrationCode->setCreatedBy(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Images>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Images $image): static
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setOwner($this);
        }

        return $this;
    }

    public function removeImage(Images $image): static
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getOwner() === $this) {
                $image->setOwner(null);
            }
        }

        return $this;
    }

}

src/Controller/CodeGeneratorController.php
<?php

namespace App\Controller;

use App\Entity\RegistrationCodes;
use App\Repository\RegistrationCodesRepository;
use App\Service\RegistrationCodeService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class CodeGeneratorController extends AbstractController
{
    #[Route('/code-inscription', name: 'app_generator')]
    public function index(Request $request, RegistrationCodeService $registrationCodeService, RegistrationCodesRepository $registrationCodesRepository, EntityManagerInterface $em): Response
    {
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login');
        }
        
        $codeList = $this->getUser()->getRegistrationCodes();

        $code = $registrationCodeService->generateCode();
        while (!is_null($registrationCodesRepository->findOneByCode($code))) {
            $code = $registrationCodeService->generateCode();
        }

        $form = $this-> createFormBuilder()->getForm();
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $registrationCode = new RegistrationCodes();
            $registrationCode -> setCode($code);
            $registrationCode -> setCreatedBy($this->getUser());

            $em->persist($registrationCode);
            $em->flush();

            return $this->redirectToRoute('app_generator');
        }

        return $this->render('code_generator/index.html.twig', [
            'codeList' => $codeList,
            'code' => $code,
            'form' => $form
        ]);
    }
}

templates/code_generator/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Codes d'inscription{% endblock %}

{% block body %}
<main class="d-flex flex-column main-default justify-content-evenly align-items-center">

    <div class="container-fluid">
           
        <div class="row justify-content-center">

            <div class="col-10 col-lg-8 col-xxl-6">
                {{ form_start(form) }}
                <section class="row pt-4 justify-content-center">
                    <div class="col-8 col-lg-6 code-box text-center p-1 p-lg-4">{{code}}</div>
                </section>
                <section class="row p-4 justify-content-center">
                    <button type="submit" class="col-10 col-lg-6 col-lg-4 btn btn-lg btn-dark mt-3">Créer le code</button>
                    

                </section>
                {{ form_end(form) }}

                
                
            </div>
        
        </div>

    </div>

    <div class="container-fluid">
           
        <div class="row justify-content-center">
            {% if codeList is not empty %}
                <div class="col-lg-3 col-4 text-center py-2 border bg-secondary lead">Code</div>
                <div class="col-lg-3 d-none d-lg-block text-center py-2 border bg-secondary lead">Création</div>
                <div class="col-lg-5 col-7 text-center py-2 border bg-secondary lead">Utilisation</div>
                {% for validCode in codeList %}
                    <div class="col-lg-3 col-4 text-center py-2 border">{{ validCode.code }}</div>
                    <div class="col-lg-3 d-none d-lg-block col-0 text-center py-2 border">{{ validCode.createdAt | date("d/m/Y") }}</div>
                    <div class="col-lg-5 col-7 text-center py-2 border">
                     {% if validCode.usedBy is null%}
                        non utilisé
                     {% else %}                        
                        {{ validCode.usedBy.email }}
                     {% endif %}
                     
                    </div>
                    
                        
                    
                {% endfor %}
                
                
            {% else %}                    
                <h1 class="text-center">Aucun code d'inscription généré</h1>
            {% endif %}
                
        </div>
    </div>

</main>

{% endblock %}